# Generated by Django 5.2.8 on 2025-11-15 23:18

import uuid

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=300)),
                (
                    "event_state_date",
                    models.DateTimeField(verbose_name="Event start time"),
                ),
                ("event_end_date", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_covers/%Y/%m/%d/"
                    ),
                ),
                (
                    "cover_photo_processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="complete",
                        max_length=20,
                    ),
                ),
                ("cover_photo_avif_url", models.TextField(blank=True)),
                ("cover_photo_webp_url", models.TextField(blank=True)),
                (
                    "photo_album_url",
                    models.URLField(blank=True, verbose_name="Photo Album URL"),
                ),
                ("short_code", models.CharField(blank=True, max_length=8, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_attendees", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("hide_attendee_count", models.BooleanField(default=False)),
                (
                    "is_listed",
                    models.BooleanField(default=True, verbose_name="Listed?"),
                ),
                (
                    "allow_rsvp",
                    models.BooleanField(default=True, verbose_name="Allow RSVP"),
                ),
                (
                    "allow_maybe_rsvp",
                    models.BooleanField(default=True, verbose_name="Allow Maybe RSVP"),
                ),
                ("reminder_24h_sent", models.BooleanField(default=False)),
                ("reminder_1h_sent", models.BooleanField(default=False)),
                (
                    "auto_reminders_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Enable auto reminders"
                    ),
                ),
                ("text_blast_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-event_state_date"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("verification_code", models.CharField(blank=True, max_length=6)),
                (
                    "verification_code_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attending", "Going"),
                            ("maybe", "Maybe"),
                            ("not_attending", "Can't Go"),
                        ],
                        default="attending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="events.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSVP",
                "verbose_name_plural": "RSVPs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TextBlast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField(max_length=500)),
                (
                    "sent_to",
                    models.CharField(
                        choices=[
                            ("attending", "Going"),
                            ("maybe", "Maybe"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("display_on_page", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_blasts",
                        to="events.event",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_text_blasts",
                        to="events.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="events.event",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to="events.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-invited_at"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to="events.user",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                blank=True, related_name="organizing_events", to="events.user"
            ),
        ),
        migrations.CreateModel(
            name="RSVPAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="events.eventquestion",
                    ),
                ),
                (
                    "rsvp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="events.rsvp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
                "ordering": ["question__order", "question__id"],
                "unique_together": {("rsvp", "question")},
            },
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(fields=["user", "event"], name="rsvp_user_event_idx"),
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(
                fields=["event", "status"], name="rsvp_event_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(fields=["user", "status"], name="rsvp_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(fields=["-created_at"], name="rsvp_created_desc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rsvp",
            unique_together={("user", "event")},
        ),
        migrations.AlterUniqueTogether(
            name="eventinvitation",
            unique_together={("event", "phone_number")},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_state_date", "is_active"], name="event_date_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_by"], name="event_creator_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["short_code"], name="event_shortcode_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["-event_state_date"], name="event_date_desc_idx"
            ),
        ),
    ]
